services:
  trae-proxy:
    image: vuldocker/trae-proxy:latest
    container_name: trae-proxy
    ports:
      - "443:443"
    volumes:
      - ./ca:/app/ca
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped